version: '3.4'

services:
  jobboard.api:
    image: ${DOCKER_REGISTRY-}jobboardapi
    container_name: jobboard.api
    build:
      context: .
      dockerfile: JobBoard.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - jobboard.database
    volumes:
      - ./.containers/jobboard-api:/app/wwwroot
  jobboard.database:
    image: mcr.microsoft.com/mssql/server
    container_name: jobboard.database
    environment:
      - MSSQL_SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - ./.containers/jobboard-database:/var/opt/mssql/data
  jobboard.frontend:
    image: ${DOCKER_REGISTRY-}jobboardui
    container_name: jobboard.frontend
    build:
      context: ./job-board-ui
      dockerfile: Dockerfile
    ports:
      - 3000:3000


